{
  description = "Desmond's Emacs (demacs) Configuration";
  nixConfig = {
    extra-substituters = [
      "https://cache.nixos.org"
      "https://nix-community.cachix.org"
      "https://demacs.cachix.org"
    ];
    extra-trusted-public-keys = [
      "cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY="
      "nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs="
      "demacs.cachix.org-1:KwSnWI5wdJm4TGdeUfmksk59098voqdDkBVNrUS7yN4="
    ];
  };
  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixpkgs-unstable";
    flake-utils.url = "github:numtide/flake-utils";
    emacs-overlay.url = "github:dezzw/emacs-overlay";

    # Emacs patches
    emacs-plus-patches = {
      url = "github:d12frosted/homebrew-emacs-plus";
      flake = false;
    };
  };
  outputs =
    inputs@{
      self,
      nixpkgs,
      flake-utils,
      emacs-overlay,
      ...
    }:
    flake-utils.lib.eachDefaultSystem (
      system:
      let
        pkgs = import nixpkgs {
          inherit system;
          overlays = [ emacs-overlay.overlay ];
        };
        lib = pkgs.lib;
      in
      rec {
        # Function to apply patches to an Emacs derivation
        applyPatches =
          emacs-base: extraPatches:
          emacs-base.overrideAttrs (old: {
            patches = (old.patches or [ ]) ++ extraPatches;
          });

        # Custom patches list (can be enabled/disabled as needed)
        customPatches = [
        ]
        ++ lib.optionals pkgs.stdenv.isLinux [

        ]
        ++ lib.optionals pkgs.stdenv.isDarwin [
          # Add setting to enable rounded window with no decoration
          "${inputs.emacs-plus-patches}/patches/emacs-31/round-undecorated-frame.patch"
          # Make Emacs aware of OS-level light/dark mode
          "${inputs.emacs-plus-patches}/patches/emacs-31/system-appearance.patch"
        ];


        emacs-igc = applyPatches pkgs.emacs-igc customPatches;

        emacs-git = applyPatches pkgs.emacs-git customPatches;

        emacs-git-pgtk = applyPatches pkgs.emacs-git-pgtk customPatches;

        # Centralized package definitions/build recipes/group lists
        packageModule = import ./packages.nix {
          inherit
            inputs
            lib
            pkgs
            ;
        };

        # Function to build emacs-augmented with a given emacs-base
        buildEmacsAugmented =
          emacs-base:
          ((pkgs.emacsPackagesFor emacs-base).emacsWithPackages (epkgs: packageModule.mkPackageList epkgs));

        # Generate an Elisp manifest that can re-add Nix-managed third-party
        # packages to `load-path' in a non-Nix Emacs for quick testing.
        mkPackageManifest =
          drv:
          let
            manifestFile = "demacs-package-paths.el";
            manifestElisp = ''
              (let* ((output-file (getenv "DEMACS_MANIFEST_OUT"))
                     (package-dirs
                      (delete-dups
                       (seq-filter
                        (lambda (dir)
                          (and (stringp dir)
                               (string-match-p "/share/emacs/site-lisp/elpa/[^/]+/?\\'" dir)))
                        load-path)))
                     (autoload-files
                      (delq nil
                            (mapcar
                             (lambda (dir)
                               (let* ((base (file-name-nondirectory (directory-file-name dir)))
                                      (autoload-file
                                       (expand-file-name (concat base "-autoloads.el") dir)))
                                 (when (file-exists-p autoload-file)
                                   autoload-file)))
                             package-dirs))))
                (with-temp-file output-file
                  (insert ";;; demacs-package-paths.el --- Generated Nix package manifest -*- lexical-binding: t -*-\n")
                  (insert ";;; Commentary:\n")
                  (insert ";; Generated by the demacs Nix build.  Load this file from a non-Nix Emacs\n")
                  (insert ";; to reuse the same third-party package closure without reinstalling it.\n\n")
                  (insert ";;; Code:\n\n")
                  (insert "(defconst demacs-nix-package-dirs\n  '")
                  (prin1 package-dirs (current-buffer))
                  (insert "\n  \"Nix-managed third-party package directories for demacs.\")\n\n")
                  (insert "(defconst demacs-nix-package-autoload-files\n  '")
                  (prin1 autoload-files (current-buffer))
                  (insert "\n  \"Autoload files belonging to `demacs-nix-package-dirs'.\")\n\n")
                  (insert "(defun demacs-activate-nix-packages ()\n")
                  (insert "  \"Add demacs Nix package directories to `load-path' and load autoloads.\"\n")
                  (insert "  (interactive)\n")
                  (insert "  (dolist (dir (reverse demacs-nix-package-dirs))\n")
                  (insert "    (add-to-list 'load-path dir))\n")
                  (insert "  (dolist (file demacs-nix-package-autoload-files)\n")
                  (insert "    (when (file-exists-p file)\n")
                  (insert "      (load file nil 'nomessage)))\n")
                  (insert "  demacs-nix-package-dirs)\n\n")
                  (insert "(demacs-activate-nix-packages)\n\n")
                  (insert "(provide 'demacs-package-paths)\n")
                  (insert ";;; demacs-package-paths.el ends here\n")))'';
          in
          pkgs.runCommand "demacs-package-manifest" { } ''
            mkdir -p "$out/share/demacs"
            export DEMACS_MANIFEST_OUT="$out/share/demacs/${manifestFile}"
            ${drv}/bin/emacs -Q --batch --eval ${lib.escapeShellArg manifestElisp}
          '';

        mkExportManifestApp =
          manifestDrv:
          pkgs.writeShellApplication {
            name = "export-demacs-package-manifest";
            text = ''
              target="''${1:-$PWD/.nix-generated/demacs-package-paths.el}"
              mkdir -p "$(dirname "$target")"
              cp "${manifestDrv}/share/demacs/demacs-package-paths.el" "$target"
              printf 'Wrote %s\n' "$target"
            '';
          };

        # ============================================================================
        # Build All Versions
        # ============================================================================

        # Build all four versions
        emacs-augmented-igc = buildEmacsAugmented emacs-igc;
        emacs-augmented-git = buildEmacsAugmented emacs-git;
        emacs-augmented-git-pgtk = buildEmacsAugmented emacs-git-pgtk;

        # ============================================================================
        # Package Outputs
        # ============================================================================

        packages.demacs-igc = emacs-augmented-igc;
        packages.demacs-git = emacs-augmented-git;
        packages.demacs-git-pgtk = emacs-augmented-git-pgtk;

        # Default is git
        packages.demacs = emacs-augmented-git;
        packages.demacs-package-manifest = mkPackageManifest packages.demacs;
        packages.default = packages.demacs;

        # ============================================================================
        # App Outputs
        # ============================================================================

        mkApp =
          name: drv:
          flake-utils.lib.mkApp {
            inherit drv;
            name = "demacs-${name}";
            exePath = "/bin/emacs";
          };

        apps.demacs-igc = mkApp "igc" packages.demacs-igc;
        apps.demacs-git = mkApp "git" packages.demacs-git;
        apps.demacs-git-pgtk = mkApp "git-pgtk" packages.demacs-git-pgtk;
        apps.export-demacs-package-manifest = flake-utils.lib.mkApp {
          drv = mkExportManifestApp packages.demacs-package-manifest;
          name = "export-demacs-package-manifest";
        };
        apps.demacs = apps.demacs-git;
        apps.default = apps.demacs;
      }
    );
}
